### PR TITLE
Idea 16 support

### PR DESCRIPTION
**Pull request by navels**

### CODE REVIEW

**Comment by rkhmelyuk** [comment]
Hey,

I just created idea16 branch. Can you merge push a PR to merge into this new branch.

**Comment by ukjbrown** [comment]
+1 for getting this merged and released ASAP. Wishing I hadn't upgraded IDEA now! Also, the main README recommends to use IDEA's Compound run configuration, but it's absolutely useless, you can't use debug or specify the start-up order! Until they sort that out, multirun should remain very much alive.

**Comment by joxzaren** [comment]
+1 on getting multirun running on Idea16. No debug with Idea's Compound run.

**Comment by ukjbrown** [comment]
I've updated and built the plug-in myself locally for now. If anyone needs it urgently, you can uninstall the 0.8 version and install from local JAR using https://github.com/ukjbrown/multirun/blob/idea15/multirun.jar

**Comment by slanska** [comment]
to ukjbrown:
Thanks a lot! Your build worked like a charm!

**Comment by ukjbrown** [comment]
@slanska no worries, hopefully @navels and @rkhmelyuk will sort out the merge and release to JetBrains repository soon. Personally if I was planning to not maintain this plugin anymore, I'd probably drop the version check completely from the plugin.xml as its more likely to break because of that than actual IntelliJ platform changes.

**Comment by navels** [comment]
FYI I posted an updated jar in this thread: https://github.com/rkhmelyuk/multirun/issues/40

**Comment by navels** [comment]
Version 1.1.3 merged to idea16 branch.

**Pull request closed without merging**
